# Generated by Django 3.1 on 2020-08-26 14:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import treewidget.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('layout', models.TextField()),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', treewidget.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='demo.equipment')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=50, unique=True, verbose_name='IP')),
                ('hostname', models.CharField(max_length=50, unique=True, verbose_name='Hostname')),
                ('name', models.CharField(max_length=50, verbose_name='Cliente')),
                ('address', models.CharField(max_length=50, verbose_name='Morada')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('equipement', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='demo.equipment')),
            ],
        ),
    ]
