# Generated by Django 3.1 on 2020-08-26 21:55

from django.db import migrations
import django.db.models.deletion
import treewidget.fields


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='equipement',
            field=treewidget.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipmenet', to='demo.equipment'),
        ),
    ]
